// Mocks generated by Mockito 5.0.16 from annotations
// in core/test/presentation/pages/serial_detail_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i11;
import 'dart:ui' as _i12;

import 'package:core/core.dart' as _i9;
import 'package:core/domain/entities/serial.dart' as _i10;
import 'package:core/domain/entities/serial_detail.dart' as _i7;
import 'package:core/domain/usecases/get_serial_detail.dart' as _i2;
import 'package:core/domain/usecases/get_serial_recommendations.dart' as _i3;
import 'package:core/domain/usecases/get_watchlist_serial_status.dart' as _i4;
import 'package:core/domain/usecases/remove_serial_watchlist.dart' as _i6;
import 'package:core/domain/usecases/save_serial_watchlist.dart' as _i5;
import 'package:core/presentation/provider/serial_detail_notifier.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeGetSerialDetail_0 extends _i1.Fake implements _i2.GetSerialDetail {}

class _FakeGetSerialRecommendations_1 extends _i1.Fake
    implements _i3.GetSerialRecommendations {}

class _FakeGetWatchListSerialStatus_2 extends _i1.Fake
    implements _i4.GetWatchListSerialStatus {}

class _FakeSaveSerialWatchlist_3 extends _i1.Fake
    implements _i5.SaveSerialWatchlist {}

class _FakeRemoveSerialWatchlist_4 extends _i1.Fake
    implements _i6.RemoveSerialWatchlist {}

class _FakeSerialDetail_5 extends _i1.Fake implements _i7.SerialDetail {}

/// A class which mocks [SerialDetailNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockSerialDetailNotifier extends _i1.Mock
    implements _i8.SerialDetailNotifier {
  MockSerialDetailNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetSerialDetail get getSerialDetail =>
      (super.noSuchMethod(Invocation.getter(#getSerialDetail),
          returnValue: _FakeGetSerialDetail_0()) as _i2.GetSerialDetail);
  @override
  _i3.GetSerialRecommendations get getSerialRecommendations =>
      (super.noSuchMethod(Invocation.getter(#getSerialRecommendations),
              returnValue: _FakeGetSerialRecommendations_1())
          as _i3.GetSerialRecommendations);
  @override
  _i4.GetWatchListSerialStatus get getWatchListStatus =>
      (super.noSuchMethod(Invocation.getter(#getWatchListStatus),
              returnValue: _FakeGetWatchListSerialStatus_2())
          as _i4.GetWatchListSerialStatus);
  @override
  _i5.SaveSerialWatchlist get saveWatchlist => (super.noSuchMethod(
      Invocation.getter(#saveWatchlist),
      returnValue: _FakeSaveSerialWatchlist_3()) as _i5.SaveSerialWatchlist);
  @override
  _i6.RemoveSerialWatchlist get removeWatchlist =>
      (super.noSuchMethod(Invocation.getter(#removeWatchlist),
              returnValue: _FakeRemoveSerialWatchlist_4())
          as _i6.RemoveSerialWatchlist);
  @override
  _i7.SerialDetail get serial => (super.noSuchMethod(Invocation.getter(#serial),
      returnValue: _FakeSerialDetail_5()) as _i7.SerialDetail);
  @override
  _i9.RequestState get serialState =>
      (super.noSuchMethod(Invocation.getter(#serialState),
          returnValue: _i9.RequestState.empty) as _i9.RequestState);
  @override
  List<_i10.Serial> get serialRecommendations =>
      (super.noSuchMethod(Invocation.getter(#serialRecommendations),
          returnValue: <_i10.Serial>[]) as List<_i10.Serial>);
  @override
  _i9.RequestState get recommendationState =>
      (super.noSuchMethod(Invocation.getter(#recommendationState),
          returnValue: _i9.RequestState.empty) as _i9.RequestState);
  @override
  String get message =>
      (super.noSuchMethod(Invocation.getter(#message), returnValue: '')
          as String);
  @override
  bool get isAddedToWatchlist =>
      (super.noSuchMethod(Invocation.getter(#isAddedToWatchlist),
          returnValue: false) as bool);
  @override
  String get watchlistMessage =>
      (super.noSuchMethod(Invocation.getter(#watchlistMessage), returnValue: '')
          as String);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  _i11.Future<void> fetchSerialDetail(int? id) => (super.noSuchMethod(
      Invocation.method(#fetchSerialDetail, [id]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i11.Future<void>);
  @override
  _i11.Future<void> addWatchlist(_i7.SerialDetail? serial) =>
      (super.noSuchMethod(Invocation.method(#addWatchlist, [serial]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i11.Future<void>);
  @override
  _i11.Future<void> removeFromWatchlist(_i7.SerialDetail? serial) =>
      (super.noSuchMethod(Invocation.method(#removeFromWatchlist, [serial]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i11.Future<void>);
  @override
  _i11.Future<void> loadWatchlistStatus(int? id) => (super.noSuchMethod(
      Invocation.method(#loadWatchlistStatus, [id]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i11.Future<void>);
  @override
  void addListener(_i12.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i12.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}
