// Mocks generated by Mockito 5.0.16 from annotations
// in core/test/presentation/provider/serial_detail_notifier_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:core/domain/entities/serial.dart' as _i9;
import 'package:core/domain/entities/serial_detail.dart' as _i7;
import 'package:core/domain/repositories/serial_repository.dart' as _i2;
import 'package:core/domain/usecases/get_serial_detail.dart' as _i4;
import 'package:core/domain/usecases/get_serial_recommendations.dart' as _i8;
import 'package:core/domain/usecases/get_watchlist_serial_status.dart' as _i10;
import 'package:core/domain/usecases/remove_serial_watchlist.dart' as _i12;
import 'package:core/domain/usecases/save_serial_watchlist.dart' as _i11;
import 'package:core/utils/failure.dart' as _i6;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeSerialRepository_0 extends _i1.Fake implements _i2.SerialRepository {
}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [GetSerialDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSerialDetail extends _i1.Mock implements _i4.GetSerialDetail {
  MockGetSerialDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SerialRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeSerialRepository_0()) as _i2.SerialRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.SerialDetail>> execute(int? id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<_i3.Either<_i6.Failure, _i7.SerialDetail>>.value(
              _FakeEither_1<_i6.Failure, _i7.SerialDetail>())) as _i5
          .Future<_i3.Either<_i6.Failure, _i7.SerialDetail>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [GetSerialRecommendations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSerialRecommendations extends _i1.Mock
    implements _i8.GetSerialRecommendations {
  MockGetSerialRecommendations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SerialRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeSerialRepository_0()) as _i2.SerialRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i9.Serial>>> execute(dynamic id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<_i3.Either<_i6.Failure, List<_i9.Serial>>>.value(
              _FakeEither_1<_i6.Failure, List<_i9.Serial>>())) as _i5
          .Future<_i3.Either<_i6.Failure, List<_i9.Serial>>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [GetWatchListSerialStatus].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchListSerialStatus extends _i1.Mock
    implements _i10.GetWatchListSerialStatus {
  MockGetWatchListSerialStatus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SerialRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeSerialRepository_0()) as _i2.SerialRepository);
  @override
  _i5.Future<bool> execute(int? id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [SaveSerialWatchlist].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveSerialWatchlist extends _i1.Mock
    implements _i11.SaveSerialWatchlist {
  MockSaveSerialWatchlist() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SerialRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeSerialRepository_0()) as _i2.SerialRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> execute(
          _i7.SerialDetail? serial) =>
      (super.noSuchMethod(Invocation.method(#execute, [serial]),
              returnValue: Future<_i3.Either<_i6.Failure, String>>.value(
                  _FakeEither_1<_i6.Failure, String>()))
          as _i5.Future<_i3.Either<_i6.Failure, String>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [RemoveSerialWatchlist].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveSerialWatchlist extends _i1.Mock
    implements _i12.RemoveSerialWatchlist {
  MockRemoveSerialWatchlist() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SerialRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeSerialRepository_0()) as _i2.SerialRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> execute(
          _i7.SerialDetail? serial) =>
      (super.noSuchMethod(Invocation.method(#execute, [serial]),
              returnValue: Future<_i3.Either<_i6.Failure, String>>.value(
                  _FakeEither_1<_i6.Failure, String>()))
          as _i5.Future<_i3.Either<_i6.Failure, String>>);
  @override
  String toString() => super.toString();
}
